"""empty message

Revision ID: fbab55528ed7
Revises: 
Create Date: 2024-01-04 19:11:09.055615

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fbab55528ed7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
